//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LimitResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class LimitResponse : object
    {
        
        private ServiceReference.Errors ErrorsField;
        
        private ServiceReference.Limits LimitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Errors Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Limits Limits
        {
            get
            {
                return this.LimitsField;
            }
            set
            {
                this.LimitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Errors", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class Errors : object
    {
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Limits", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class Limits : object
    {
        
        private decimal DailyLimitField;
        
        private decimal LineLimitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DailyLimit
        {
            get
            {
                return this.DailyLimitField;
            }
            set
            {
                this.DailyLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineLimit
        {
            get
            {
                return this.LineLimitField;
            }
            set
            {
                this.LineLimitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantStatementSourceStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class MerchantStatementSourceStatusResponse : object
    {
        
        private bool CreditCardsProcessedField;
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreditCardsProcessed
        {
            get
            {
                return this.CreditCardsProcessedField;
            }
            set
            {
                this.CreditCardsProcessedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MandateOptions.MandateDebitFrequency", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum MandateOptionsMandateDebitFrequency : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bimonthly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeMonthly = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SixMonthly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annually = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Biweekly = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MandateOptions.MandatePublicHolidayOption", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum MandateOptionsMandatePublicHolidayOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrecedingOrdinaryBusinessDay = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryNextOrdinaryBusinessDay = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MandateOptions.BankAccountType", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum MandateOptionsBankAccountType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Current = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Savings = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transmission = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MandateOptions.Title", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum MandateOptionsTitle : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mr = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mrs = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Miss = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dr = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prof = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ms = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rabbi = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ds = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adv = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckOptions.CollectionFrequencyDayCodes", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum DebiCheckOptionsCollectionFrequencyDayCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_01 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_02 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_03 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_04 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_05 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_06 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEEK_07 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_01 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_02 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_03 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_04 = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_05 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_06 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_07 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_08 = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_09 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_10 = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_11 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_12 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_13 = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTN_14 = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_01 = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_02 = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_03 = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_04 = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_05 = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_06 = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_07 = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_08 = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_09 = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_10 = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_11 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_12 = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_13 = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_14 = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_15 = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_16 = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_17 = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_18 = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_19 = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_20 = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_21 = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_22 = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_23 = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_24 = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_25 = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_26 = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_27 = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_28 = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_29 = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_30 = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNTH_31 = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_01 = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_02 = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_03 = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_04 = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_05 = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_06 = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_07 = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_08 = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_09 = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_10 = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_11 = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_12 = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_13 = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_14 = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_15 = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_16 = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_17 = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_18 = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_19 = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_20 = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_21 = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_22 = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_23 = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_24 = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_25 = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_26 = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_27 = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_28 = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_29 = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_30 = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QURT_31 = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_01 = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_02 = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_03 = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_04 = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_05 = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_06 = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_07 = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_08 = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_09 = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_10 = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_11 = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_12 = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_13 = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_14 = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_15 = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_16 = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_17 = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_18 = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_19 = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_20 = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_21 = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_22 = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_23 = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_24 = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_25 = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_26 = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_27 = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_28 = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_29 = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_30 = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MIAN_31 = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YEAR_01 = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_01 = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_02 = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_03 = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_04 = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_05 = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_06 = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_07 = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_08 = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_09 = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_10 = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_11 = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_12 = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_13 = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADHO_14 = 129,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NIWSResponseContainer", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.GetAvailableBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.DebiCheckAuthenticateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.DebiCheckAuthenticationCurrentStatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.GetPostbackVerifyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.AccountFundsTransferResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.AVSRealtimeQueryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.DebiCheckAmendmentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.DebiCheckMandateTemplateDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.RetrieveBlockedAccountsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.AddMandateResponse))]
    public partial class NIWSResponseContainer : object
    {
        
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAvailableBalanceResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class GetAvailableBalanceResponse : ServiceReference.NIWSResponseContainer
    {
        
        private decimal AvailableBalanceField;
        
        private decimal CurrentBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableBalance
        {
            get
            {
                return this.AvailableBalanceField;
            }
            set
            {
                this.AvailableBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentBalance
        {
            get
            {
                return this.CurrentBalanceField;
            }
            set
            {
                this.CurrentBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckAuthenticateResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class DebiCheckAuthenticateResponse : ServiceReference.NIWSResponseContainer
    {
        
        private string BankResponseCodeField;
        
        private string BankservResponseCodeField;
        
        private string ClientResponseCodeField;
        
        private string ContractReferenceField;
        
        private string[] MessagesField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankResponseCode
        {
            get
            {
                return this.BankResponseCodeField;
            }
            set
            {
                this.BankResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankservResponseCode
        {
            get
            {
                return this.BankservResponseCodeField;
            }
            set
            {
                this.BankservResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientResponseCode
        {
            get
            {
                return this.ClientResponseCodeField;
            }
            set
            {
                this.ClientResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractReference
        {
            get
            {
                return this.ContractReferenceField;
            }
            set
            {
                this.ContractReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckAuthenticationCurrentStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class DebiCheckAuthenticationCurrentStatusResponse : ServiceReference.NIWSResponseContainer
    {
        
        private string CancellationReasonField;
        
        private string ContractReferenceField;
        
        private string DateCancelledField;
        
        private string StatusField;
        
        private string UpdateDateField;
        
        private string BankservResponseField;
        
        private string BankResponseField;
        
        private string ClientResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancellationReason
        {
            get
            {
                return this.CancellationReasonField;
            }
            set
            {
                this.CancellationReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractReference
        {
            get
            {
                return this.ContractReferenceField;
            }
            set
            {
                this.ContractReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateCancelled
        {
            get
            {
                return this.DateCancelledField;
            }
            set
            {
                this.DateCancelledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateDate
        {
            get
            {
                return this.UpdateDateField;
            }
            set
            {
                this.UpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string BankservResponse
        {
            get
            {
                return this.BankservResponseField;
            }
            set
            {
                this.BankservResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string BankResponse
        {
            get
            {
                return this.BankResponseField;
            }
            set
            {
                this.BankResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ClientResponse
        {
            get
            {
                return this.ClientResponseField;
            }
            set
            {
                this.ClientResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPostbackVerifyResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class GetPostbackVerifyResponse : ServiceReference.NIWSResponseContainer
    {
        
        private System.Collections.Generic.Dictionary<string, string> FormVariablesField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> FormVariables
        {
            get
            {
                return this.FormVariablesField;
            }
            set
            {
                this.FormVariablesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountFundsTransferResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class AccountFundsTransferResponse : ServiceReference.NIWSResponseContainer
    {
        
        private string RequestTraceField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestTrace
        {
            get
            {
                return this.RequestTraceField;
            }
            set
            {
                this.RequestTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AVSRealtimeQueryResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class AVSRealtimeQueryResponse : ServiceReference.NIWSResponseContainer
    {
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AcceptsCreditsField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AcceptsDebitsField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AccountActiveField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AccountDormantField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> BankAccountNumberValidField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> EmailMatchField;
        
        private string FileTokenField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> IdNumberMatchField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> InitialMatchField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> LastNameMatchField;
        
        private string[] MessagesField;
        
        private bool OfflineRequestField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> PeriodActiveField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> PhoneNumberMatchField;
        
        private System.Nullable<ServiceReference.AVSOptionsMatchIndicator> TaxRefMatchField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AcceptsCredits
        {
            get
            {
                return this.AcceptsCreditsField;
            }
            set
            {
                this.AcceptsCreditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AcceptsDebits
        {
            get
            {
                return this.AcceptsDebitsField;
            }
            set
            {
                this.AcceptsDebitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AccountActive
        {
            get
            {
                return this.AccountActiveField;
            }
            set
            {
                this.AccountActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> AccountDormant
        {
            get
            {
                return this.AccountDormantField;
            }
            set
            {
                this.AccountDormantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> BankAccountNumberValid
        {
            get
            {
                return this.BankAccountNumberValidField;
            }
            set
            {
                this.BankAccountNumberValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> EmailMatch
        {
            get
            {
                return this.EmailMatchField;
            }
            set
            {
                this.EmailMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileToken
        {
            get
            {
                return this.FileTokenField;
            }
            set
            {
                this.FileTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> IdNumberMatch
        {
            get
            {
                return this.IdNumberMatchField;
            }
            set
            {
                this.IdNumberMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> InitialMatch
        {
            get
            {
                return this.InitialMatchField;
            }
            set
            {
                this.InitialMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> LastNameMatch
        {
            get
            {
                return this.LastNameMatchField;
            }
            set
            {
                this.LastNameMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OfflineRequest
        {
            get
            {
                return this.OfflineRequestField;
            }
            set
            {
                this.OfflineRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> PeriodActive
        {
            get
            {
                return this.PeriodActiveField;
            }
            set
            {
                this.PeriodActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> PhoneNumberMatch
        {
            get
            {
                return this.PhoneNumberMatchField;
            }
            set
            {
                this.PhoneNumberMatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.AVSOptionsMatchIndicator> TaxRefMatch
        {
            get
            {
                return this.TaxRefMatchField;
            }
            set
            {
                this.TaxRefMatchField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckAmendmentResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class DebiCheckAmendmentResponse : ServiceReference.NIWSResponseContainer
    {
        
        private string ContractReferenceField;
        
        private string[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractReference
        {
            get
            {
                return this.ContractReferenceField;
            }
            set
            {
                this.ContractReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckMandateTemplateDetail", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class DebiCheckMandateTemplateDetail : ServiceReference.NIWSResponseContainer
    {
        
        private string AdjustmentAmountField;
        
        private string AdjustmentCategoryField;
        
        private string AdjustmentRuleIndicatorField;
        
        private string AdjustmentTypeField;
        
        private string AuthenticationTypeField;
        
        private string CollectionFrequencyField;
        
        private string CollectionFrequencyDayCodeField;
        
        private string DebitEntryClassCodeField;
        
        private string DebitValueTypeField;
        
        private string DebtorAuthCodeField;
        
        private string DebtorAuthenticationRequiredField;
        
        private string[] InitiationDayOptionsField;
        
        private string InstallmentOccurrenceField;
        
        private string RMSField;
        
        private string TemplateIdField;
        
        private string TemplateNameField;
        
        private string TrackingDayCodeField;
        
        private string TrackingIndicatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdjustmentAmount
        {
            get
            {
                return this.AdjustmentAmountField;
            }
            set
            {
                this.AdjustmentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdjustmentCategory
        {
            get
            {
                return this.AdjustmentCategoryField;
            }
            set
            {
                this.AdjustmentCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdjustmentRuleIndicator
        {
            get
            {
                return this.AdjustmentRuleIndicatorField;
            }
            set
            {
                this.AdjustmentRuleIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdjustmentType
        {
            get
            {
                return this.AdjustmentTypeField;
            }
            set
            {
                this.AdjustmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationType
        {
            get
            {
                return this.AuthenticationTypeField;
            }
            set
            {
                this.AuthenticationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionFrequency
        {
            get
            {
                return this.CollectionFrequencyField;
            }
            set
            {
                this.CollectionFrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionFrequencyDayCode
        {
            get
            {
                return this.CollectionFrequencyDayCodeField;
            }
            set
            {
                this.CollectionFrequencyDayCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitEntryClassCode
        {
            get
            {
                return this.DebitEntryClassCodeField;
            }
            set
            {
                this.DebitEntryClassCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitValueType
        {
            get
            {
                return this.DebitValueTypeField;
            }
            set
            {
                this.DebitValueTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtorAuthCode
        {
            get
            {
                return this.DebtorAuthCodeField;
            }
            set
            {
                this.DebtorAuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtorAuthenticationRequired
        {
            get
            {
                return this.DebtorAuthenticationRequiredField;
            }
            set
            {
                this.DebtorAuthenticationRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] InitiationDayOptions
        {
            get
            {
                return this.InitiationDayOptionsField;
            }
            set
            {
                this.InitiationDayOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallmentOccurrence
        {
            get
            {
                return this.InstallmentOccurrenceField;
            }
            set
            {
                this.InstallmentOccurrenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMS
        {
            get
            {
                return this.RMSField;
            }
            set
            {
                this.RMSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateId
        {
            get
            {
                return this.TemplateIdField;
            }
            set
            {
                this.TemplateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName
        {
            get
            {
                return this.TemplateNameField;
            }
            set
            {
                this.TemplateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingDayCode
        {
            get
            {
                return this.TrackingDayCodeField;
            }
            set
            {
                this.TrackingDayCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingIndicator
        {
            get
            {
                return this.TrackingIndicatorField;
            }
            set
            {
                this.TrackingIndicatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveBlockedAccountsResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class RetrieveBlockedAccountsResponse : ServiceReference.NIWSResponseContainer
    {
        
        private ServiceReference.BlockedAccount[] BlockedAccountsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.BlockedAccount[] BlockedAccounts
        {
            get
            {
                return this.BlockedAccountsField;
            }
            set
            {
                this.BlockedAccountsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMandateResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class AddMandateResponse : ServiceReference.NIWSResponseContainer
    {
        
        private string[] ErrorsField;
        
        private string MandateUrlField;
        
        private string[] WarningsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MandateUrl
        {
            get
            {
                return this.MandateUrlField;
            }
            set
            {
                this.MandateUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings
        {
            get
            {
                return this.WarningsField;
            }
            set
            {
                this.WarningsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AVSOptions.MatchIndicator", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum AVSOptionsMatchIndicator : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotApplicable = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlockedAccount", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class BlockedAccount : object
    {
        
        private string AccountNameField;
        
        private string AccountNumberField;
        
        private string ActionDateField;
        
        private decimal BankAccountNumberField;
        
        private string BlackListTypeField;
        
        private decimal BranchCodeField;
        
        private string DateBlockedField;
        
        private string DescriptionField;
        
        private string UnpaidCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDate
        {
            get
            {
                return this.ActionDateField;
            }
            set
            {
                this.ActionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BankAccountNumber
        {
            get
            {
                return this.BankAccountNumberField;
            }
            set
            {
                this.BankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlackListType
        {
            get
            {
                return this.BlackListTypeField;
            }
            set
            {
                this.BlackListTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateBlocked
        {
            get
            {
                return this.DateBlockedField;
            }
            set
            {
                this.DateBlockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnpaidCode
        {
            get
            {
                return this.UnpaidCodeField;
            }
            set
            {
                this.UnpaidCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisteredMandateOptions.DebtorIdentification", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum RegisteredMandateOptionsDebtorIdentification : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        I = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebiCheckOptions.CancellationReasonCodes", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public enum DebiCheckOptionsCancellationReasonCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AGNT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CURR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUST = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUTA = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUPL = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRAD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPAY = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRTR = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveProofOfPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS")]
    public partial class RetrieveProofOfPaymentResponse : object
    {
        
        private string ErrorCodeField;
        
        private string ProofOfPaymentPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProofOfPaymentPDF
        {
            get
            {
                return this.ProofOfPaymentPDFField;
            }
            set
            {
                this.ProofOfPaymentPDFField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.INIWS_NIF")]
    public interface INIWS_NIF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/GetPaymentLimits", ReplyAction="http://tempuri.org/INIWS_NIF/GetPaymentLimitsResponse")]
        System.Threading.Tasks.Task<ServiceReference.LimitResponse> GetPaymentLimitsAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/GetDebitLimits", ReplyAction="http://tempuri.org/INIWS_NIF/GetDebitLimitsResponse")]
        System.Threading.Tasks.Task<ServiceReference.LimitResponse> GetDebitLimitsAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/AccountFundsRelease", ReplyAction="http://tempuri.org/INIWS_NIF/AccountFundsReleaseResponse")]
        System.Threading.Tasks.Task<string> AccountFundsReleaseAsync(string ServiceKey, string Date, long AmountInCents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestActionDate", ReplyAction="http://tempuri.org/INIWS_NIF/RequestActionDateResponse")]
        System.Threading.Tasks.Task<string> RequestActionDateAsync(string ServiceKey, string Date, string Instruction, string ForwardActionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestPresentationDate", ReplyAction="http://tempuri.org/INIWS_NIF/RequestPresentationDateResponse")]
        System.Threading.Tasks.Task<string> RequestPresentationDateAsync(string ServiceKey, string Date, string Instruction, string ForwardActionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestInterimMerchantStatement", ReplyAction="http://tempuri.org/INIWS_NIF/RequestInterimMerchantStatementResponse")]
        System.Threading.Tasks.Task<string> RequestInterimMerchantStatementAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestMerchantStatement", ReplyAction="http://tempuri.org/INIWS_NIF/RequestMerchantStatementResponse")]
        System.Threading.Tasks.Task<string> RequestMerchantStatementAsync(string ServiceKey, string FromActionDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveMerchantStatement", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveMerchantStatementResponse")]
        System.Threading.Tasks.Task<string> RetrieveMerchantStatementAsync(string ServiceKey, string PollingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestTransactionTypes", ReplyAction="http://tempuri.org/INIWS_NIF/RequestTransactionTypesResponse")]
        System.Threading.Tasks.Task<string> RequestTransactionTypesAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveTransactionTypes", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveTransactionTypesResponse")]
        System.Threading.Tasks.Task<string> RetrieveTransactionTypesAsync(string ServiceKey, string PollingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/LegacyCompactBatchFileUpload", ReplyAction="http://tempuri.org/INIWS_NIF/LegacyCompactBatchFileUploadResponse")]
        System.Threading.Tasks.Task<string> LegacyCompactBatchFileUploadAsync(string UserName, string Password, string PIN, string File, string ProcessAsLegacy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/LegacyBatchFileUpload", ReplyAction="http://tempuri.org/INIWS_NIF/LegacyBatchFileUploadResponse")]
        System.Threading.Tasks.Task<string> LegacyBatchFileUploadAsync(string UserName, string Password, string PIN, string File, string ProcessAsLegacy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/BatchFileUpload", ReplyAction="http://tempuri.org/INIWS_NIF/BatchFileUploadResponse")]
        System.Threading.Tasks.Task<string> BatchFileUploadAsync(string ServiceKey, string File);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestFileUploadReport", ReplyAction="http://tempuri.org/INIWS_NIF/RequestFileUploadReportResponse")]
        System.Threading.Tasks.Task<string> RequestFileUploadReportAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestCombinedUploadReportForDate", ReplyAction="http://tempuri.org/INIWS_NIF/RequestCombinedUploadReportForDateResponse")]
        System.Threading.Tasks.Task<string> RequestCombinedUploadReportForDateAsync(string ServiceKey, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestCreditDataReport", ReplyAction="http://tempuri.org/INIWS_NIF/RequestCreditDataReportResponse")]
        System.Threading.Tasks.Task<string[]> RequestCreditDataReportAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestAVSReport", ReplyAction="http://tempuri.org/INIWS_NIF/RequestAVSReportResponse")]
        System.Threading.Tasks.Task<string> RequestAVSReportAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestPayNowInvoice", ReplyAction="http://tempuri.org/INIWS_NIF/RequestPayNowInvoiceResponse")]
        System.Threading.Tasks.Task<string> RequestPayNowInvoiceAsync(string serviceKey, string fileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/IsValidServiceKey", ReplyAction="http://tempuri.org/INIWS_NIF/IsValidServiceKeyResponse")]
        System.Threading.Tasks.Task<string[]> IsValidServiceKeyAsync(string MethodKey, string ServiceKey, string InstructionCode, int SofwareVendorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/AccountServiceKeys", ReplyAction="http://tempuri.org/INIWS_NIF/AccountServiceKeysResponse")]
        System.Threading.Tasks.Task<string[]> AccountServiceKeysAsync(string MethodKey, string AccountNo, int SoftwareVendorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/MerchantStatementSourceStatus", ReplyAction="http://tempuri.org/INIWS_NIF/MerchantStatementSourceStatusResponse")]
        System.Threading.Tasks.Task<ServiceReference.MerchantStatementSourceStatusResponse> MerchantStatementSourceStatusAsync(string ServiceKey, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestDebitBatchUnauthorised", ReplyAction="http://tempuri.org/INIWS_NIF/RequestDebitBatchUnauthorisedResponse")]
        System.Threading.Tasks.Task<string> RequestDebitBatchUnauthorisedAsync(string ServiceKey, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveBatchStatus", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveBatchStatusResponse")]
        System.Threading.Tasks.Task<string> RetrieveBatchStatusAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveSpecificBatchStatus", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveSpecificBatchStatusResponse")]
        System.Threading.Tasks.Task<string> RetrieveSpecificBatchStatusAsync(string ServiceKey, string BatchName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveMultipleBatchStatus", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveMultipleBatchStatusResponse")]
        System.Threading.Tasks.Task<string> RetrieveMultipleBatchStatusAsync(string ServiceKey, int NumberOfBatches);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveBatchStatusByDate", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveBatchStatusByDateResponse")]
        System.Threading.Tasks.Task<string> RetrieveBatchStatusByDateAsync(string ServiceKey, string StartDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveUnauthorisedBatches", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveUnauthorisedBatchesResponse")]
        System.Threading.Tasks.Task<string> RetrieveUnauthorisedBatchesAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestBatchAuthorise", ReplyAction="http://tempuri.org/INIWS_NIF/RequestBatchAuthoriseResponse")]
        System.Threading.Tasks.Task<string> RequestBatchAuthoriseAsync(string ServiceKey, System.Guid BatchIndicator, bool SendEmail, string FromName, string FromAddress, bool SendSMS, bool ReleaseFunds, bool BankTransfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RequestMandateData", ReplyAction="http://tempuri.org/INIWS_NIF/RequestMandateDataResponse")]
        System.Threading.Tasks.Task<string> RequestMandateDataAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveMandateData", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveMandateDataResponse")]
        System.Threading.Tasks.Task<string> RetrieveMandateDataAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveMandatePDF", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveMandatePDFResponse")]
        System.Threading.Tasks.Task<string> RetrieveMandatePDFAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/AddMandate", ReplyAction="http://tempuri.org/INIWS_NIF/AddMandateResponse")]
        System.Threading.Tasks.Task<ServiceReference.AddMandateResponse> AddMandateAsync(
                    string ServiceKey, 
                    string AccountReference, 
                    string MandateName, 
                    decimal MandateAmount, 
                    bool IsConsumer, 
                    string FirstName, 
                    string Surname, 
                    string TradingName, 
                    string RegistrationNumber, 
                    string RegisteredName, 
                    string MobileNumber, 
                    ServiceReference.MandateOptionsMandateDebitFrequency DebitFrequency, 
                    int CommencementMonth, 
                    string CommencementDay, 
                    string AgreementDate, 
                    string AgreementReferenceNumber, 
                    System.Nullable<int> CancellationNoticePeriod, 
                    System.Nullable<ServiceReference.MandateOptionsMandatePublicHolidayOption> PublicHolidayOption, 
                    string Notes, 
                    string Field1, 
                    string Field2, 
                    string Field3, 
                    string Field4, 
                    string Field5, 
                    string Field6, 
                    string Field7, 
                    string Field8, 
                    string Field9, 
                    System.Nullable<bool> AllowVariableDebitAmounts, 
                    System.Nullable<int> BankDetailType, 
                    string BankAccountName, 
                    string BankAccountNumber, 
                    string BranchCode, 
                    System.Nullable<ServiceReference.MandateOptionsBankAccountType> BankAccountType, 
                    string CreditCardToken, 
                    System.Nullable<int> CreditCardType, 
                    System.Nullable<int> ExpiryMonth, 
                    System.Nullable<int> ExpiryYear, 
                    System.Nullable<bool> IsIdNumber, 
                    System.Nullable<ServiceReference.MandateOptionsTitle> Title, 
                    string EmailAddress, 
                    string PhoneNumber, 
                    string DateOfBirth, 
                    string DecemberDebitDay, 
                    string DebitMasterfileGroup, 
                    string PhysicalAddressLine1, 
                    string PhysicalAddressLine2, 
                    string PhysicalAddressLine3, 
                    string PhysicalSuburb, 
                    string PhysicalCity, 
                    string PhysicalProvince, 
                    string PhysicalPostalCode, 
                    System.Nullable<bool> MandateActive, 
                    System.Nullable<bool> RequestAVS, 
                    string AVSCheckNumber, 
                    bool IncludeDebiCheck, 
                    string DebiCheckMandateTemplateId, 
                    System.Nullable<decimal> DebiCheckCollectionAmount, 
                    System.Nullable<bool> DebiCheckFirstCollectionDiffers, 
                    string DebiCheckFirstCollectionDate, 
                    System.Nullable<decimal> DebiCheckFirstCollectionAmount, 
                    System.Nullable<ServiceReference.DebiCheckOptionsCollectionFrequencyDayCodes> DebiCheckCollectionDayCode, 
                    System.Nullable<bool> AddToMasterFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/GetAvailableBalance", ReplyAction="http://tempuri.org/INIWS_NIF/GetAvailableBalanceResponse")]
        System.Threading.Tasks.Task<ServiceReference.GetAvailableBalanceResponse> GetAvailableBalanceAsync(string serviceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/DebiCheckAuthenticate", ReplyAction="http://tempuri.org/INIWS_NIF/DebiCheckAuthenticateResponse")]
        System.Threading.Tasks.Task<ServiceReference.DebiCheckAuthenticateResponse> DebiCheckAuthenticateAsync(
                    string ServiceKey, 
                    string AccountReference, 
                    string DebiCheckMandateTemplateId, 
                    bool IsIdNumber, 
                    string DebtorIdentification, 
                    string AccountName, 
                    string BankAccountName, 
                    string BranchCode, 
                    string BankAccountNumber, 
                    ServiceReference.MandateOptionsBankAccountType BankAccountType, 
                    string MobileNumber, 
                    string EmailAddress, 
                    decimal CollectionAmount, 
                    bool FirstCollectionDiffers, 
                    System.Nullable<decimal> FirstCollectionAmount, 
                    string FirstCollectionDate, 
                    System.Nullable<ServiceReference.DebiCheckOptionsCollectionFrequencyDayCodes> collectionDayCode, 
                    System.Nullable<ServiceReference.RegisteredMandateOptionsDebtorIdentification> DebtorIdentificationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/DebiCheckCancelAuthentication", ReplyAction="http://tempuri.org/INIWS_NIF/DebiCheckCancelAuthenticationResponse")]
        System.Threading.Tasks.Task<string> DebiCheckCancelAuthenticationAsync(string ServiceKey, string ContractReference, ServiceReference.DebiCheckOptionsCancellationReasonCodes reasonCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/DebiCheckAuthenticationCurrentStatus", ReplyAction="http://tempuri.org/INIWS_NIF/DebiCheckAuthenticationCurrentStatusResponse")]
        System.Threading.Tasks.Task<ServiceReference.DebiCheckAuthenticationCurrentStatusResponse> DebiCheckAuthenticationCurrentStatusAsync(string ServiceKey, string ContractReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/PostbackVerify", ReplyAction="http://tempuri.org/INIWS_NIF/PostbackVerifyResponse")]
        System.Threading.Tasks.Task<ServiceReference.GetPostbackVerifyResponse> PostbackVerifyAsync(string ServiceKey, int pbid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/AccountFundsTransfer", ReplyAction="http://tempuri.org/INIWS_NIF/AccountFundsTransferResponse")]
        System.Threading.Tasks.Task<ServiceReference.AccountFundsTransferResponse> AccountFundsTransferAsync(string ServiceKey, string ToAccountNumber, string BeneficiaryReference, long AmountInCents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/AVSRealtimeQuery", ReplyAction="http://tempuri.org/INIWS_NIF/AVSRealtimeQueryResponse")]
        System.Threading.Tasks.Task<ServiceReference.AVSRealtimeQueryResponse> AVSRealtimeQueryAsync(string ServiceKey, string AccountReference, string Extra1, string Extra2, string Extra3, string BankAccountNumber, string BranchCode, ServiceReference.MandateOptionsBankAccountType BankAccountType, string EnquiryName, string Initials, string IdNumber, bool IsIdNumber, string PhoneNumber, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/DebiCheckAmendAuthentication", ReplyAction="http://tempuri.org/INIWS_NIF/DebiCheckAmendAuthenticationResponse")]
        System.Threading.Tasks.Task<ServiceReference.DebiCheckAmendmentResponse> DebiCheckAmendAuthenticationAsync(string ServiceKey, string ContractReference, System.Nullable<long> CollectionAmountInCents, System.Nullable<long> MaximumCollectionAmountInCents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/DebiCheckRetrieveMandateTemplateDetail", ReplyAction="http://tempuri.org/INIWS_NIF/DebiCheckRetrieveMandateTemplateDetailResponse")]
        System.Threading.Tasks.Task<ServiceReference.DebiCheckMandateTemplateDetail> DebiCheckRetrieveMandateTemplateDetailAsync(string ServiceKey, string DebiCheckMandateTemplateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveProofOfPayment", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveProofOfPaymentResponse")]
        System.Threading.Tasks.Task<ServiceReference.RetrieveProofOfPaymentResponse> RetrieveProofOfPaymentAsync(string ServiceKey, int TransactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_NIF/RetrieveBlockedAccounts", ReplyAction="http://tempuri.org/INIWS_NIF/RetrieveBlockedAccountsResponse")]
        System.Threading.Tasks.Task<ServiceReference.RetrieveBlockedAccountsResponse> RetrieveBlockedAccountsAsync(string ServiceKey, string StartDate, string EndDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface INIWS_NIFChannel : ServiceReference.INIWS_NIF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class NIWS_NIFClient : System.ServiceModel.ClientBase<ServiceReference.INIWS_NIF>, ServiceReference.INIWS_NIF
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NIWS_NIFClient() : 
                base(NIWS_NIFClient.GetDefaultBinding(), NIWS_NIFClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INIWS_NIF.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIWS_NIFClient(EndpointConfiguration endpointConfiguration) : 
                base(NIWS_NIFClient.GetBindingForEndpoint(endpointConfiguration), NIWS_NIFClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIWS_NIFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NIWS_NIFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIWS_NIFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NIWS_NIFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NIWS_NIFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LimitResponse> GetPaymentLimitsAsync(string ServiceKey)
        {
            return base.Channel.GetPaymentLimitsAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LimitResponse> GetDebitLimitsAsync(string ServiceKey)
        {
            return base.Channel.GetDebitLimitsAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> AccountFundsReleaseAsync(string ServiceKey, string Date, long AmountInCents)
        {
            return base.Channel.AccountFundsReleaseAsync(ServiceKey, Date, AmountInCents);
        }
        
        public System.Threading.Tasks.Task<string> RequestActionDateAsync(string ServiceKey, string Date, string Instruction, string ForwardActionDate)
        {
            return base.Channel.RequestActionDateAsync(ServiceKey, Date, Instruction, ForwardActionDate);
        }
        
        public System.Threading.Tasks.Task<string> RequestPresentationDateAsync(string ServiceKey, string Date, string Instruction, string ForwardActionDate)
        {
            return base.Channel.RequestPresentationDateAsync(ServiceKey, Date, Instruction, ForwardActionDate);
        }
        
        public System.Threading.Tasks.Task<string> RequestInterimMerchantStatementAsync(string ServiceKey)
        {
            return base.Channel.RequestInterimMerchantStatementAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> RequestMerchantStatementAsync(string ServiceKey, string FromActionDate)
        {
            return base.Channel.RequestMerchantStatementAsync(ServiceKey, FromActionDate);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveMerchantStatementAsync(string ServiceKey, string PollingId)
        {
            return base.Channel.RetrieveMerchantStatementAsync(ServiceKey, PollingId);
        }
        
        public System.Threading.Tasks.Task<string> RequestTransactionTypesAsync(string ServiceKey)
        {
            return base.Channel.RequestTransactionTypesAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveTransactionTypesAsync(string ServiceKey, string PollingId)
        {
            return base.Channel.RetrieveTransactionTypesAsync(ServiceKey, PollingId);
        }
        
        public System.Threading.Tasks.Task<string> LegacyCompactBatchFileUploadAsync(string UserName, string Password, string PIN, string File, string ProcessAsLegacy)
        {
            return base.Channel.LegacyCompactBatchFileUploadAsync(UserName, Password, PIN, File, ProcessAsLegacy);
        }
        
        public System.Threading.Tasks.Task<string> LegacyBatchFileUploadAsync(string UserName, string Password, string PIN, string File, string ProcessAsLegacy)
        {
            return base.Channel.LegacyBatchFileUploadAsync(UserName, Password, PIN, File, ProcessAsLegacy);
        }
        
        public System.Threading.Tasks.Task<string> BatchFileUploadAsync(string ServiceKey, string File)
        {
            return base.Channel.BatchFileUploadAsync(ServiceKey, File);
        }
        
        public System.Threading.Tasks.Task<string> RequestFileUploadReportAsync(string ServiceKey, string FileToken)
        {
            return base.Channel.RequestFileUploadReportAsync(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<string> RequestCombinedUploadReportForDateAsync(string ServiceKey, string Date)
        {
            return base.Channel.RequestCombinedUploadReportForDateAsync(ServiceKey, Date);
        }
        
        public System.Threading.Tasks.Task<string[]> RequestCreditDataReportAsync(string ServiceKey, string FileToken)
        {
            return base.Channel.RequestCreditDataReportAsync(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<string> RequestAVSReportAsync(string ServiceKey, string FileToken)
        {
            return base.Channel.RequestAVSReportAsync(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<string> RequestPayNowInvoiceAsync(string serviceKey, string fileToken)
        {
            return base.Channel.RequestPayNowInvoiceAsync(serviceKey, fileToken);
        }
        
        public System.Threading.Tasks.Task<string[]> IsValidServiceKeyAsync(string MethodKey, string ServiceKey, string InstructionCode, int SofwareVendorCode)
        {
            return base.Channel.IsValidServiceKeyAsync(MethodKey, ServiceKey, InstructionCode, SofwareVendorCode);
        }
        
        public System.Threading.Tasks.Task<string[]> AccountServiceKeysAsync(string MethodKey, string AccountNo, int SoftwareVendorCode)
        {
            return base.Channel.AccountServiceKeysAsync(MethodKey, AccountNo, SoftwareVendorCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.MerchantStatementSourceStatusResponse> MerchantStatementSourceStatusAsync(string ServiceKey, string Date)
        {
            return base.Channel.MerchantStatementSourceStatusAsync(ServiceKey, Date);
        }
        
        public System.Threading.Tasks.Task<string> RequestDebitBatchUnauthorisedAsync(string ServiceKey, string Date)
        {
            return base.Channel.RequestDebitBatchUnauthorisedAsync(ServiceKey, Date);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveBatchStatusAsync(string ServiceKey)
        {
            return base.Channel.RetrieveBatchStatusAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveSpecificBatchStatusAsync(string ServiceKey, string BatchName)
        {
            return base.Channel.RetrieveSpecificBatchStatusAsync(ServiceKey, BatchName);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveMultipleBatchStatusAsync(string ServiceKey, int NumberOfBatches)
        {
            return base.Channel.RetrieveMultipleBatchStatusAsync(ServiceKey, NumberOfBatches);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveBatchStatusByDateAsync(string ServiceKey, string StartDate, string EndDate)
        {
            return base.Channel.RetrieveBatchStatusByDateAsync(ServiceKey, StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveUnauthorisedBatchesAsync(string ServiceKey)
        {
            return base.Channel.RetrieveUnauthorisedBatchesAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> RequestBatchAuthoriseAsync(string ServiceKey, System.Guid BatchIndicator, bool SendEmail, string FromName, string FromAddress, bool SendSMS, bool ReleaseFunds, bool BankTransfer)
        {
            return base.Channel.RequestBatchAuthoriseAsync(ServiceKey, BatchIndicator, SendEmail, FromName, FromAddress, SendSMS, ReleaseFunds, BankTransfer);
        }
        
        public System.Threading.Tasks.Task<string> RequestMandateDataAsync(string ServiceKey)
        {
            return base.Channel.RequestMandateDataAsync(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveMandateDataAsync(string ServiceKey, string FileToken)
        {
            return base.Channel.RetrieveMandateDataAsync(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveMandatePDFAsync(string ServiceKey, string FileToken)
        {
            return base.Channel.RetrieveMandatePDFAsync(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AddMandateResponse> AddMandateAsync(
                    string ServiceKey, 
                    string AccountReference, 
                    string MandateName, 
                    decimal MandateAmount, 
                    bool IsConsumer, 
                    string FirstName, 
                    string Surname, 
                    string TradingName, 
                    string RegistrationNumber, 
                    string RegisteredName, 
                    string MobileNumber, 
                    ServiceReference.MandateOptionsMandateDebitFrequency DebitFrequency, 
                    int CommencementMonth, 
                    string CommencementDay, 
                    string AgreementDate, 
                    string AgreementReferenceNumber, 
                    System.Nullable<int> CancellationNoticePeriod, 
                    System.Nullable<ServiceReference.MandateOptionsMandatePublicHolidayOption> PublicHolidayOption, 
                    string Notes, 
                    string Field1, 
                    string Field2, 
                    string Field3, 
                    string Field4, 
                    string Field5, 
                    string Field6, 
                    string Field7, 
                    string Field8, 
                    string Field9, 
                    System.Nullable<bool> AllowVariableDebitAmounts, 
                    System.Nullable<int> BankDetailType, 
                    string BankAccountName, 
                    string BankAccountNumber, 
                    string BranchCode, 
                    System.Nullable<ServiceReference.MandateOptionsBankAccountType> BankAccountType, 
                    string CreditCardToken, 
                    System.Nullable<int> CreditCardType, 
                    System.Nullable<int> ExpiryMonth, 
                    System.Nullable<int> ExpiryYear, 
                    System.Nullable<bool> IsIdNumber, 
                    System.Nullable<ServiceReference.MandateOptionsTitle> Title, 
                    string EmailAddress, 
                    string PhoneNumber, 
                    string DateOfBirth, 
                    string DecemberDebitDay, 
                    string DebitMasterfileGroup, 
                    string PhysicalAddressLine1, 
                    string PhysicalAddressLine2, 
                    string PhysicalAddressLine3, 
                    string PhysicalSuburb, 
                    string PhysicalCity, 
                    string PhysicalProvince, 
                    string PhysicalPostalCode, 
                    System.Nullable<bool> MandateActive, 
                    System.Nullable<bool> RequestAVS, 
                    string AVSCheckNumber, 
                    bool IncludeDebiCheck, 
                    string DebiCheckMandateTemplateId, 
                    System.Nullable<decimal> DebiCheckCollectionAmount, 
                    System.Nullable<bool> DebiCheckFirstCollectionDiffers, 
                    string DebiCheckFirstCollectionDate, 
                    System.Nullable<decimal> DebiCheckFirstCollectionAmount, 
                    System.Nullable<ServiceReference.DebiCheckOptionsCollectionFrequencyDayCodes> DebiCheckCollectionDayCode, 
                    System.Nullable<bool> AddToMasterFile)
        {
            return base.Channel.AddMandateAsync(ServiceKey, AccountReference, MandateName, MandateAmount, IsConsumer, FirstName, Surname, TradingName, RegistrationNumber, RegisteredName, MobileNumber, DebitFrequency, CommencementMonth, CommencementDay, AgreementDate, AgreementReferenceNumber, CancellationNoticePeriod, PublicHolidayOption, Notes, Field1, Field2, Field3, Field4, Field5, Field6, Field7, Field8, Field9, AllowVariableDebitAmounts, BankDetailType, BankAccountName, BankAccountNumber, BranchCode, BankAccountType, CreditCardToken, CreditCardType, ExpiryMonth, ExpiryYear, IsIdNumber, Title, EmailAddress, PhoneNumber, DateOfBirth, DecemberDebitDay, DebitMasterfileGroup, PhysicalAddressLine1, PhysicalAddressLine2, PhysicalAddressLine3, PhysicalSuburb, PhysicalCity, PhysicalProvince, PhysicalPostalCode, MandateActive, RequestAVS, AVSCheckNumber, IncludeDebiCheck, DebiCheckMandateTemplateId, DebiCheckCollectionAmount, DebiCheckFirstCollectionDiffers, DebiCheckFirstCollectionDate, DebiCheckFirstCollectionAmount, DebiCheckCollectionDayCode, AddToMasterFile);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetAvailableBalanceResponse> GetAvailableBalanceAsync(string serviceKey)
        {
            return base.Channel.GetAvailableBalanceAsync(serviceKey);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DebiCheckAuthenticateResponse> DebiCheckAuthenticateAsync(
                    string ServiceKey, 
                    string AccountReference, 
                    string DebiCheckMandateTemplateId, 
                    bool IsIdNumber, 
                    string DebtorIdentification, 
                    string AccountName, 
                    string BankAccountName, 
                    string BranchCode, 
                    string BankAccountNumber, 
                    ServiceReference.MandateOptionsBankAccountType BankAccountType, 
                    string MobileNumber, 
                    string EmailAddress, 
                    decimal CollectionAmount, 
                    bool FirstCollectionDiffers, 
                    System.Nullable<decimal> FirstCollectionAmount, 
                    string FirstCollectionDate, 
                    System.Nullable<ServiceReference.DebiCheckOptionsCollectionFrequencyDayCodes> collectionDayCode, 
                    System.Nullable<ServiceReference.RegisteredMandateOptionsDebtorIdentification> DebtorIdentificationCode)
        {
            return base.Channel.DebiCheckAuthenticateAsync(ServiceKey, AccountReference, DebiCheckMandateTemplateId, IsIdNumber, DebtorIdentification, AccountName, BankAccountName, BranchCode, BankAccountNumber, BankAccountType, MobileNumber, EmailAddress, CollectionAmount, FirstCollectionDiffers, FirstCollectionAmount, FirstCollectionDate, collectionDayCode, DebtorIdentificationCode);
        }
        
        public System.Threading.Tasks.Task<string> DebiCheckCancelAuthenticationAsync(string ServiceKey, string ContractReference, ServiceReference.DebiCheckOptionsCancellationReasonCodes reasonCode)
        {
            return base.Channel.DebiCheckCancelAuthenticationAsync(ServiceKey, ContractReference, reasonCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DebiCheckAuthenticationCurrentStatusResponse> DebiCheckAuthenticationCurrentStatusAsync(string ServiceKey, string ContractReference)
        {
            return base.Channel.DebiCheckAuthenticationCurrentStatusAsync(ServiceKey, ContractReference);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetPostbackVerifyResponse> PostbackVerifyAsync(string ServiceKey, int pbid)
        {
            return base.Channel.PostbackVerifyAsync(ServiceKey, pbid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AccountFundsTransferResponse> AccountFundsTransferAsync(string ServiceKey, string ToAccountNumber, string BeneficiaryReference, long AmountInCents)
        {
            return base.Channel.AccountFundsTransferAsync(ServiceKey, ToAccountNumber, BeneficiaryReference, AmountInCents);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AVSRealtimeQueryResponse> AVSRealtimeQueryAsync(string ServiceKey, string AccountReference, string Extra1, string Extra2, string Extra3, string BankAccountNumber, string BranchCode, ServiceReference.MandateOptionsBankAccountType BankAccountType, string EnquiryName, string Initials, string IdNumber, bool IsIdNumber, string PhoneNumber, string Email)
        {
            return base.Channel.AVSRealtimeQueryAsync(ServiceKey, AccountReference, Extra1, Extra2, Extra3, BankAccountNumber, BranchCode, BankAccountType, EnquiryName, Initials, IdNumber, IsIdNumber, PhoneNumber, Email);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DebiCheckAmendmentResponse> DebiCheckAmendAuthenticationAsync(string ServiceKey, string ContractReference, System.Nullable<long> CollectionAmountInCents, System.Nullable<long> MaximumCollectionAmountInCents)
        {
            return base.Channel.DebiCheckAmendAuthenticationAsync(ServiceKey, ContractReference, CollectionAmountInCents, MaximumCollectionAmountInCents);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DebiCheckMandateTemplateDetail> DebiCheckRetrieveMandateTemplateDetailAsync(string ServiceKey, string DebiCheckMandateTemplateId)
        {
            return base.Channel.DebiCheckRetrieveMandateTemplateDetailAsync(ServiceKey, DebiCheckMandateTemplateId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetrieveProofOfPaymentResponse> RetrieveProofOfPaymentAsync(string ServiceKey, int TransactionId)
        {
            return base.Channel.RetrieveProofOfPaymentAsync(ServiceKey, TransactionId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetrieveBlockedAccountsResponse> RetrieveBlockedAccountsAsync(string ServiceKey, string StartDate, string EndDate)
        {
            return base.Channel.RetrieveBlockedAccountsAsync(ServiceKey, StartDate, EndDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INIWS_NIF))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INIWS_NIF))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.netcash.co.za/NIWS/NIWS_NIF.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NIWS_NIFClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INIWS_NIF);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NIWS_NIFClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INIWS_NIF);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INIWS_NIF,
        }
    }
}
